#############################################################################
# Makefile for building: ShowListing
# Generated by qmake (3.0) (Qt 5.1.0) on: sam. 21. sept. 13:47:59 2013
# Project:  ShowListing.pro
# Template: app
# Command: C:\Qt5\qt-5.1.0-msvc2012-x86\qtbase\bin\qmake.exe -spec win32-msvc2012 -o Makefile ShowListing.pro
#############################################################################

MAKEFILE      = Makefile

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = C:\Qt5\qt-5.1.0-msvc2012-x86\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: ShowListing.pro ..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\win32-msvc2012\qmake.conf ..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\spec_pre.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\common\shell-win32.conf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\qconfig.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_axbase.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_axbase.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_axcontainer.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_axserver.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_axserver.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_bootstrap.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_clucene.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_clucene.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_core.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_declarative.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_declarative.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_gui.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_help.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_help.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_network.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_opengl.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_platformsupport.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_qml.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_qml.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_qmldevtools.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_quick.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_quick.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_quickparticles.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_quickparticles.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_script.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_script.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_sensors.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_serialport.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_serialport.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_sql.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_svg.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_svg.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_uitools.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_v8.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_v8.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_xml.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qico.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qminimal.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmldbg_inspector.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp_qtdeclarative.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmng.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qsvg.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qsvgicon.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtaccessiblequick.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtaccessiblewidgets.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtga.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtiff.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtsensors_dummy.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtsensors_generic.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qwbmp.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qwindows.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_dumpcpp.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_dumpdoc.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_idc.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_lconvert.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_lrelease.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_lupdate.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qdoc.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qmlbundle.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qmlmin.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qmlscene.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qmltestrunner.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_uic.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_xmlpatterns.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\qt_functions.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\qt_config.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\win32-msvc2012\qmake.conf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\spec_post.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\exclusive_builds.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\default_pre.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\win32\default_pre.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\resolve_config.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\default_post.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\win32\rtti.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\warn_on.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\qt.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\resources.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\moc.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\win32\opengl.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\uic.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\win32\windows.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\testcase_targets.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\exceptions.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\yacc.prf \
		..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\lex.prf \
		ShowListing.pro \
		C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5Widgets.prl \
		C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5Gui.prl \
		C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5Core.prl \
		C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5Xml.prl \
		C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/plugins/platforms/qwindows.prl \
		C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5PlatformSupport.prl
	$(QMAKE) -spec win32-msvc2012 -o Makefile ShowListing.pro
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\spec_pre.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\common\shell-win32.conf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\qconfig.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_axbase.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_axbase.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_axcontainer.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_axserver.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_axserver.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_bootstrap.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_clucene.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_clucene.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_core.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_declarative.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_declarative.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_help.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_help.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_multimedia.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_multimediawidgets.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_network.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_opengl.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_platformsupport.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_qml.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_qmldevtools.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_qmldevtools.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_qmltest.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_qtmultimediaquicktools.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_quick.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_quickparticles.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_quickparticles.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_script.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_script.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_scripttools.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_sensors.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_serialport.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_svg.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_uitools.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_uitools.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_v8.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_v8.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules-inst\qt_lib_xmlpatterns.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qico.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qminimal.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmldbg_inspector.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmldbg_qtquick2.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmldbg_tcp_qtdeclarative.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qmng.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qsvg.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qsvgicon.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtaccessiblequick.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtaccessiblewidgets.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtga.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtiff.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtmedia_audioengine.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtmultimedia_m3u.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_plugin.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtsensorgestures_shakeplugin.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtsensors_dummy.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qtsensors_generic.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qwbmp.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_qwindows.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_dumpcpp.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_dumpdoc.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_idc.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_lconvert.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_lrelease.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_lupdate.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qdoc.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qmlbundle.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qmlmin.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qmlscene.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_qmltestrunner.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_uic.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_xmlpatterns.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\modules\qt_tool_xmlpatternsvalidator.pri:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\qt_functions.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\qt_config.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\win32-msvc2012\qmake.conf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\spec_post.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\exclusive_builds.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\default_pre.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\win32\default_pre.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\resolve_config.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\default_post.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\win32\rtti.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\warn_on.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\qt.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\resources.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\moc.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\win32\opengl.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\uic.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\win32\windows.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\testcase_targets.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\exceptions.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\yacc.prf:
..\..\Qt5\qt-everywhere-opensource-src-5.1.0-msvc2012-build\qtbase\mkspecs\features\lex.prf:
ShowListing.pro:
C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5Widgets.prl:
C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5Gui.prl:
C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5Core.prl:
C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5Xml.prl:
C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/plugins/platforms/qwindows.prl:
C:/Qt5/qt-everywhere-opensource-src-5.1.0-msvc2012-build/qtbase/lib/Qt5PlatformSupport.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2012 -o Makefile ShowListing.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) C:\work\qt_ShowListing\showlisting_plugin_import.cpp

release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
